version: "3.9"
services:
  spark-main:
    image: learn-spark
    command:
      - "main-node"
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - sparknet

  spark-worker-1:
    image: learn-spark
    command:
      - "worker-node"
    ports:
      - "8081:8081"
    environment:
      - "MAIN_HOST=spark-main"
    depends_on:
      - spark-main
    networks:
      - sparknet

  spark-worker-2:
    image: learn-spark
    command:
      - "worker-node"
    ports:
      - "8082:8081"
    environment:
      - "MAIN_HOST=spark-main"
    depends_on:
      - spark-main
    networks:
      - sparknet

  spark-worker-3:
    image: learn-spark
    command:
      - "worker-node"
    ports:
      - "8083:8081"
    environment:
      - "MAIN_HOST=spark-main"
    depends_on:
      - spark-main
    networks:
      - sparknet

networks:
  sparknet:
