version: "3.9"
services:
  spark-main:
    image: learn-spark
    command:
      - "main-node"
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - sparknet
    volumes:
      - /tmp/spark:/spark_shared

  spark-worker-1:
    image: learn-spark
    command:
      - "worker-node"
    ports:
      - "8081:8081"
    depends_on:
      - spark-main
    networks:
      - sparknet
    volumes:
      - /tmp/spark:/spark_shared

  spark-worker-2:
    image: learn-spark
    command:
      - "worker-node"
    ports:
      - "8082:8081"
    depends_on:
      - spark-main
    networks:
      - sparknet
    volumes:
      - /tmp/spark:/spark_shared

  spark-history:
    image: learn-spark
    command:
      - "history-server"
    ports:
      - "18080:18080"
    depends_on:
      - spark-main
      - spark-worker-1
      - spark-worker-2
    networks:
      - sparknet
    volumes:
      - /tmp/spark:/spark_shared

networks:
  sparknet:
